version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - "3309:3306"
    volumes:
      - ./raw:/raw
      - ./coldp:/var/lib/mysql-files/
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: convert
  gnparser:
    image: gnames/gnparser
  conversion:
    build:
      context: .
      dockerfile: ./docker/conversion.Dockerfile
    depends_on:
      - database
      - gnparser
    volumes:
      - ./raw:/raw
      - ./scripts:/home/col
      - ./scan:/home/col/scan
      - ./coldp:/var/lib/mysql-files
    entrypoint: python /home/col/convert.py